### ISSUE TITLE
Binary Classification vs Regression

### ISSUE THREAD

**Issue by and-rewsmith** [bshaw19/Crypto_Trader#2]
I feel as if it would be a better idea to have a regression for predicted price for the next time window (whatever increment we end up choosing).

This is because, in the scenario the price goes up, it is only profitable to trade when the expected profit exceeds trade costs (gas). If we had context for the price increase we could avoid losing money on negligible increases. 

Thoughts?

**Comment by bshaw2019** [comment]
I definitely agree that a regression model is more appropriate for projected price/profit. 

The main function of the classifier is generating a confidence value that the price will increase or decrease using a confusion matrix.

Perhaps we should split the trading pair scoring process into two separate models, a regressor and a classifier. These could be used to generate predictions for both reward (projected profit from the regressor) and risk (the confidence value for a price increase or decrease move). I think building these models for a variety of timeframes for all symbols (example: 1 min price change, 5 min, 15 min, 30 min, 1 hour) will provide the Q-learning trader with enough information to determine an optimized trading strategy that both reduces risk and rewards profit.

**Comment by andrewvaliente** [comment]
regression for prices, classification for tweets
