### ISSUE TITLE
Paper:Algorithmic Trading of Cryptocurrency Based on Twitter Sentiment Analysis

### ISSUE THREAD

**Issue by tonywangcn** [bshaw19/Crypto_Trader#4]
Algorithmic Trading of Cryptocurrency Based on Twitter Sentiment Analysis
http://cs229.stanford.edu/proj2015/029_report.pdf

share some papers about algo trading of crypto here

**Comment by bshaw2019** [comment]
This was a great paper thank you very much for the lead!
